export const SELLER_RATING_TAGS = [
  "FRESH_PRODUCE",
  "FAIR_PRICE",
  "GOOD_BEHAVIOR",
  "GOOD_COMMUNICATION",
  "QUANTITY_AVAILABLE",
  "PRICE_DIFFERENT",
  "STOCK_UNAVAILABLE",
  "QUALITY_ISSUE",
] as const;

export const RATING_ELIGIBILITY_REASON = {
  CONTACT_REQUIRED: "CONTACT_REQUIRED",
  WAITING_PERIOD: "WAITING_PERIOD",
} as const;