import axios from "axios";

import { ApiError } from "../../../utils/ApiError";

interface Msg91VerifiedUser {
  identifier?: string;
  mobile?: string;
  mobileNumber?: string;

  [key: string]: unknown;
}

interface Msg91VerifyResponse {
  type?: string;
  message?: string;
  data?: Msg91VerifiedUser;

  [key: string]: unknown;
}

/**
 * Verifies the access token generated by the MSG91 OTP Widget.
 *
 * Important:
 * - accessToken comes from frontend after verifyOtp() succeeds.
 * - Auth Key must stay only on the backend.
 */
export async function verifyMsg91AccessToken(
  msgAccessToken: string,
): Promise<Msg91VerifyResponse> {
  const authKey = process.env.MSG91_AUTH_KEY;

  const verifyUrl = process.env.MSG91_VERIFY_TOKEN_URL;

  if (!authKey) {
    throw new Error("MSG91_AUTH_KEY is not configured.");
  }

  if (!verifyUrl) {
    throw new Error("MSG91_VERIFY_TOKEN_URL is not configured.");
  }

  try {
    const response = await axios.post<Msg91VerifyResponse>(
      verifyUrl,

      // MSG91 expects the access token as a field
      {
        "access-token": msgAccessToken,
      },

      {
        headers: {
          authkey: authKey,

          "Content-Type": "application/json",
        },
      },
    );

    console.log("MSG91 verified response:", response.data);

    if (response.data.type === "error" || response.data.hasError) {
      throw new ApiError(
        401,
        response.data.message ?? "MSG91 token verification failed.",
      );
    }

    return response.data;
  } catch (error) {
    if (error instanceof ApiError) {
      throw error;
    }

    if (axios.isAxiosError(error)) {
      console.error(
        "MSG91 access token verification failed:",
        error.response?.data,
      );

      throw new ApiError(
        401,
        error.response?.data?.message ?? "Phone verification failed.",
      );
    }

    throw error;
  }
}
